version: 2

project_name: apikit

builds:
  - id: apikit
    dir: cmd
    main: ./apikit
    binary: apikit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: 'Documentation'
      regexp: '^.*?docs(\(.+\))?\!?:.+$'
      order: 2
    - title: 'Other'
      order: 999
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kausys
    name: apikit
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
