package authz

import "context"

// Enforcer checks whether a subject has a given permission.
// P is the project-defined permission type (e.g., generated by apikit authz gen).
// Implementations may use casbin, OPA, or any other policy engine.
type Enforcer[P any] interface {
	Enforce(ctx context.Context, subjectID string, perm P) (bool, error)
}
