openapi: 3.1.2
info:
    title: API
    version: 1.0.0
paths:
    /health:
        get:
            tags:
                - health
            operationId: healthCheck
            responses: {}
components: {}
